@startuml 组件图
node 办公机房 {
    database mysql [
        卡信息
        订单信息
    ] 
    node 卡信息管理系统
    node 打印机
    卡信息管理系统 --> mysql
    卡信息管理系统 --> 打印机
}

node 食堂收款机
node 管理中心浏览器

食堂收款机 --> 卡信息管理系统
管理中心浏览器 --> 卡信息管理系统








@enduml