@startuml

== 注册充值 == 
   操作人员 -> 卡管理模块: 注册
   卡管理模块 -> 卡账户: 创建
   卡账户 -> 卡管理模块: 新建卡账号
   卡管理模块 -> 卡管理模块: 记录身份
   卡管理模块 -> 操作人员: 卡信息

   操作人员 -> 卡管理模块: 充值金额
   卡管理模块 -> 卡管理模块: 记录充值订单
   卡管理模块 -> 卡账户: 增加余额
   卡账户 -> 卡管理模块: 返回成功
   卡管理模块 -> 操作人员: 返回成功

== 消费 == 
   操作人员 -> 收银台: 插入卡
   收银台 -> 卡管理模块: 查询卡信息
   卡管理模块 -> 卡管理模块: 查询卡信息
   卡管理模块 -> 卡账户: 查询余额
   卡账户 -> 卡管理模块: 卡余额
   卡管理模块 -> 收银台: 卡信息
   收银台 -> 操作人员: 卡信息

   操作人员 -> 收银台: 扣除金额
   收银台 -> 卡管理模块: 查询卡信息
   卡管理模块 -> 卡管理模块: 记录消费订单
   卡管理模块 -> 卡账户: 扣除余额
   卡账户 -> 卡管理模块: 返回成功
   卡管理模块 -> 收银台: 返回成功
   收银台 -> 操作人员: 返回成功

== 监控 == 
    操作人员 -> 卡管理模块: 查询卡号,时间范围
    卡管理模块 -> 卡管理模块: 查询订单列表
    操作人员 <- 卡管理模块: 返回订单列表
    操作人员 -> 卡管理模块: 选择打印卡号,时间范围
    卡管理模块 -> 卡管理模块: 查询订单列表
    卡管理模块 -> 打印模块: 订单列表信息
    打印模块 -> 打印模块: 调用打印机
    卡管理模块 <- 打印模块: 返回成功
    操作人员 <- 卡管理模块: 返回成功
@enduml

component 卡账户 as account
    component 监控模块 as monitor 
    component 卡管理模块 as accountManage
    component 收银台 as pay
    component 打印模块 as printer