@startuml

服务消费程序 -> 服务框架客户端 : 服务接口参数和名称
服务框架客户端 -> 服务提供管理器 : 服务接口名称
服务提供管理器 -> 服务框架客户端 : 服务可访问域名列表
服务框架客户端 -> 负载均衡器 : 服务可访域名列表,接口名称,参数
负载均衡器 -> 服务框架客户端 : 访问的对应IP
服务框架客户端 -> 远程通讯模块 : 服务接口参数和名称，请求对应IP
远程通讯模块 ->  服务提供者远程通讯模块 : 请求消息体
服务提供者远程通讯模块 -> 服务框架服务端 : 请求消息体
服务框架服务端 -> 服务提供者程序 : 调用服务对应方法
服务提供者程序 -> 服务框架服务端 : 返回方法结果
服务框架服务端 -> 服务提供者远程通讯模块 : 结果消息体
服务提供者远程通讯模块 -> 远程通讯模块 : 结果消息体
远程通讯模块 -> 服务框架客户端 : 结果消息体
服务框架客户端 -> 服务消费程序 : 方法结果
@enduml